services:
  - type: web
    name: parcial3-ml
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app/app.py --server.port $PORT --server.address 0.0.0.0"
    runtime: "python3.11"
